name: Ajouter un participant

on:
  workflow_dispatch:
    inputs:
      prenom:
        description: 'Prénom'
        required: true
      nom:
        description: 'Nom'
        required: true
      soumission:
        description: 'Soumission'
        required: true

jobs:
  ajouter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ajouter dans le JSON
        run: |
          FILE="docs/data/participants.json"
          NEW="{\"Prenom\": \"${{ github.event.inputs.prenom }}\", \"Nom\": \"${{ github.event.inputs.nom }}\", \"Soumission\": ${{ github.event.inputs.soumission }}}"
          CONTENT=$(cat "$FILE")
          echo "$CONTENT" | jq ".participants += [ $NEW ]" > "$FILE"

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git add "$FILE"
          git commit -m "Ajout de ${{ github.event.inputs.prenom }} ${{ github.event.inputs.nom }} (Soumission ${{ github.event.inputs.soumission }})"
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
